### ISSUE TITLE
Error: spawn EACCES on MacOS

### ISSUE THREAD

**Issue by Jonsoncao** [SabakiHQ/LeelaSabaki#11]
>internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^
>Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at childProcess.spawn (pkg/prelude/bootstrap.js:1392:27)
    at new GTPEngine (/snapshot/LeelaSabaki/src/GTPEngine.js:10:24)
    at Object.<anonymous> (/snapshot/LeelaSabaki/src/index.js:36:14)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)

I am having this issue at startup of LeelaSabaki using

>./leelasabaki --heatmap path/leela-zero/src -w path/leela-zero/weights.txt --playouts 100 --noponder 

My node and npm are installed using Homebrew.

**Comment by yishn** [comment]
It seems like you put the path to Leela Zeros source code directory in the arguments? Please download an executable and put the path to the executable file as the argument after `--heatmap`.

**Comment by Jonsoncao** [comment]
Sorry for the confusion. My Leela Z's binary is in the same directory as the source code. I have no problem using Leela Zero in Sabaki using
>--gtp --weights path/leela-zero/weights.txt -p 500 --noponder

**Comment by yishn** [comment]
But you still have to specify the path to the binary file, not to the directory. Can you post your Sabaki engine settings for LeelaSabaki and Leela Zero in its entirety?

**Comment by Jonsoncao** [comment]
[Screenshot](https://i.imgur.com/QVWSYlq.png)

This is a screenshot of my current setting. Leela Zero is good, LeelaSabaki is not.

**Comment by yishn** [comment]
As I said, you're specifying a folder name to LeelaSabaki. Try the following arguments:

~~~
--heatmap /Users/scao/Documents/leela-zero/src/leelaz -w /Users/scao/Documents/leela-zero/weights.txt -p 500 --noponder
~~~

**Comment by Jonsoncao** [comment]
Now I am feeling I am stupid and not reading the manual carefully enough. Thanks for the patience.

**Comment by yishn** [comment]
No problem! I assume this issue has been solved.
