### ISSUE TITLE
How to get the % Winrate below the game tree?

### ISSUE THREAD

**Issue by HarryLi98** [SabakiHQ/LeelaSabaki#19]
Hi, I have everything working except I don't know how to get the %WR below the game tree.
My argument is currently:
--heatmap D:\Downloads\leela-zero-0.15-win64\leela-zero-0.15-win64\leelaz.exe -w D:\Downloads\leela-zero-0.15-win64\leela-zero-0.15-win64\networks\b69158ea816e75b7ffea06142d90d2b1199b48265e75e292f3d5bd3c081d78ee --playouts 100 --noponder
Also curious to see full list of arguments I can use. Thanks in advance.

**Comment by yishn** [comment]
The win rate information are in the comments. A list of available arguments is located in the README.
