### ISSUE TITLE
Leela zero crashes in start (maybe my config)

### ISSUE THREAD

**Issue by lmhsjackson** [SabakiHQ/LeelaSabaki#20]
I cant get leela zero to work with sabaki. 
This is my config:
![image](https://user-images.githubusercontent.com/1307528/41911645-9737808e-7923-11e8-866e-c8a81311ff3b.png)

This is the error I am getting:
![image](https://user-images.githubusercontent.com/1307528/41911662-a9193a9a-7923-11e8-8980-9b1cc0958f6f.png)

Leela seems to be working fine running from console.
![image](https://user-images.githubusercontent.com/1307528/41911805-0e133b12-7924-11e8-91d7-5546577fedb0.png)

**Comment by yishn** [comment]
Try removing the `--gtp` flag.

**Comment by lmhsjackson** [comment]
worked like a charm, thank you!
