### ISSUE TITLE
Trouble with libOpenCL version information

### ISSUE THREAD

**Issue by DableUTeeF** [SabakiHQ/LeelaSabaki#21]
I used command `./leelasabaki /home/palm/leela-zero/build/leelaz` and got `/home/palm/leela-zero/build/leelaz: /usr/local/cuda/lib64/libOpenCL.so.1: no version information available (required by /home/palm/leela-zero/build/leelaz)`.
But if I use `./leelasabaki /home/palm/leela-zero/build/leelaz --weights /home/palm/leela-zero/build/best-network --gtp`, it just like a normal leela when I run in command

Normal Sabaki works fine in my machine.

Sorry for my gramma

**Comment by yishn** [comment]
I'm not sure what the problem is. Seems like everything is working fine? For Leila Zero, specifying a weights file is a must.

**Comment by DableUTeeF** [comment]
I entered the weights file path but the GUI was not show

**Comment by yishn** [comment]
Please read [the installation guide](https://github.com/SabakiHQ/LeelaSabaki#installation) carefully. For the GUI, you have to use Sabaki.
