### ISSUE TITLE
Integrate into Sabaki

### ISSUE THREAD

**Issue by hadim** [SabakiHQ/LeelaSabaki#24]
While the engine manager in Sabaki is nice and allow flexibility in the use of different engines, it would be nice to have a default one directly integrated into Sabaki.

Maybe we could find a way to add new engines trough npm dependency. That would be an alternative to the current binary command line based engines.

The npm plugin would expose a JS class with known methods to be called during the use of the engine.

**Comment by yishn** [comment]
All popular Go engines that I know of are licensed under GPL, which makes it somewhat a legal greyzone to include them into an MIT licensed work such as Sabaki. Lizzie is licensed under GPL as well, so it's fine over there. Apart from any legal reasons, I also do not want to be compelled to release a new version of Sabaki every time the integrated engine releases a new version.

Adding engines via a dependency manager is not a bad idea, but most users (especially non-developers) do not have npm, let alone Node.js.

**Comment by yishn** [comment]
Oh, in that case: LeelaSabaki will be obsolete in the upcoming version of Sabaki, because of the integrated analysis feature that uses the GTP analyze command. Currently only Leela Zero supports it.

**Comment by hadim** [comment]
Perfect then.

**Comment by hadim** [comment]
What do you think about auto-downloading the best available binary of Leela (if available)? They do that in Lizzie and it's a great feature.

https://github.com/featurecat/lizzie/blob/a82c8ec08eef6c587276f6e1b7d8da16ee89c8e7/src/main/java/featurecat/lizzie/analysis/Leelaz.java#L145

**Comment by hadim** [comment]
In the `analysis` branch of Sabaki of course.

**Comment by yishn** [comment]
You mean the network file? That's just too Leela Zero specific, so no.
