### ISSUE TITLE
Crash "Cannot read property 'isSquare' of null" - LZ vs LZ match

### ISSUE THREAD

**Issue by odeint** [SabakiHQ/LeelaSabaki#3]
Hi,

I was running a match between two different weightfiles using the same LeelaSabaki and LeelaZ executables (just different command line options in the engine management). After about 100 moves, Sabaki freezes and crashes with this popup:

![image](https://user-images.githubusercontent.com/8819119/34687073-f31c4948-f4ad-11e7-8ed3-4cb8a5a44d02.png)

One thing I noticed as well is that both players keep decreasing their "Thinking at most XX seconds" at every move. It starts at 50.0 and then counts down by 0.2s with the small weightfiles (5x64) and by 0.4s per move with the large weightfile (6x128 supervised). Not sure if that has anything to do with it, I tried with lower playouts so they don't get clipped by time; the crash still happens.

**Comment by odeint** [comment]
PS: Sabaki doesn't actually totally freeze, it seems just the LeelaSabaki Engine crashes out and the match stops. I was able to save the two .sgf files after all, they end at the moment of the crash.

The LeelaZ version was the 0.10.1 Win64 binary, LeelaSabaki v0.2.0 was also the Win binary.

[sgf_files_from_crash.zip](https://github.com/yishn/LeelaSabaki/files/1612737/sgf_files_from_crash.zip)

**Comment by yishn** [comment]
I've encountered this issue before as well, but I think I might have solved it in the new release. Can you update Sabaki and LeelaSabaki to see if you can reproduce this issue?

**Comment by odeint** [comment]
I just tested resuming from a saved .sgf that crashes with the old version after one move for each player (I can then reattach and repeat the cycle). With Sabaki v0.33.0 & LeelaSabaki v0.3.0 this now runs without crashing for until the end of the game. The "Thinking at most XX second" still counts down, though. I'll test tomorrow what happens when this gets too low for the playout setting.

**Comment by yishn** [comment]
Since there wasn't a response, I'll assume everything is in working order.
