### ISSUE TITLE
Does not work with Mac

### ISSUE THREAD

**Issue by agentneigh** [SabakiHQ/LeelaSabaki#6]
Tested several different ways and does not launch.

**Comment by raspingbard** [comment]
Agreed, I can’t get LeelaSabaki to run on my Mac.  I’ve only tried running it with the basic Leela 0.11, not Leela Zero.  After I enter the engine setup and start a new game, the GTP console will look like this:

-     LeelaSabaki> name
      ?NaN Sabaki v0.3.0

-     LeelaSabaki> version
      ?NaN :
               leelasabaki [—flat] …

-     LeelaSabaki> protocol_version
      ?NaN NS:
            —flat …

-     LeelaSabaki> list_commands
      ?NaN tmap….

Then, when I click on the board for my first move, I get this error message:
     "Current board arrangement can’t be recreated on the GTP engine."

After that, it just says “connection error” for each GTP command.  See attached screenshots.  I'm running Sabaki v0.33.2 on an iMac OS 10.13.1.

<img width="1137" alt="screen shot 2018-02-10 at 4 05 59 pm" src="https://user-images.githubusercontent.com/28121941/36067682-3cb6ee4c-0e7f-11e8-853c-6d2d1233207a.png">
<img width="993" alt="screen shot 2018-02-10 at 4 07 50 pm" src="https://user-images.githubusercontent.com/28121941/36067683-3cc78c02-0e7f-11e8-8f14-a10ec4e6771f.png">

**Comment by yishn** [comment]
@raspingbard It seems you are specifying the `--help` flag. LeelaSabaki only displays a help message when this flag is given and therefore it won't enter GTP mode or start Leela.

**Comment by yishn** [comment]
Since @raspingbard is able to run LeelaSabaki without problems (The help message is being displayed after all), I will close this issue.

**Comment by raspingbard** [comment]
Strange, I thought I had first tried it without the "--help" option and it didn't work.  That's when I tried the "--help" option.  Anyway, I removed the "--help" and "-g" options both and it started working.  Thanks for your help.

**Comment by raspingbard** [comment]
@agentneigh  In addition to the above guidelines, you need to enable executable permission on the LeelaSabaki file in the Terminal utility:
        chmod +x <file>

Also, make sure you have entered the Leela path in quotes (if there are any spaces in the path) in the Manage Engines dialog.
