### ISSUE TITLE
this peice of crap doesn't work

### ISSUE THREAD

**Issue by hydrogenpi** [SabakiHQ/LeelaSabaki#9]
sabaki not working, stupid command line syntax issues, sabaki leela is convoluted pile of $*!%, sabaki has to interface with sabaki-leela, then sabaki-leela has to interfac with node.js, then that interface with leelz which interface with the network weights... , unnecessarily complicated steps, Sabaki shoudl just work with leelaz out the box, we have two different versions of leela, four different versions of alphago, and two different versions of sabaki, three different network sizes, even the example syntax doesn't make it clear if it could be / or \ and if the thing could be on single or double quotes I mean wtf

**Comment by yishn** [comment]
Guess what? You don't have to use it. This is an open source project. Feel free to improve it.
